### ISSUE TITLE
Add ReadMe for the project and mention the deployed api docs in the readme.

### ISSUE THREAD

**Issue by srihariash999** [srihariash999/moneyboi_backend#9]
- Improve the repo visibility and approchability by adding readme to the project.
- Readme should outline the basic functionality and idea of this repo.(Backend for [MoneyBoi Project](https://github.com/srihariash999/moneyboi) )
- Should also contain a link to the backend docs which is already hosted.
- Should also contain a link to the frontend app's repo.

**Comment by georgioupanayiotis** [comment]
@srihariash999 can you please assign me this issue ?

**Comment by srihariash999** [comment]
@georgioupanayiotis You can work on this, please check this repo and the frontend repo associated with this and proceed. I will accept the PR.

**Comment by georgioupanayiotis** [comment]
@srihariash999 i have created the PR here https://github.com/srihariash999/moneyboi_backend/pull/10

### Preview

![Screenshot 2022-10-08 at 3 28 26 PM](https://user-images.githubusercontent.com/1752156/194707641-0f079105-6e50-486f-bea8-a9f0a38f232d.png)

**Comment by georgioupanayiotis** [comment]
@srihariash999  it would be very helpful if you can please review it as soon as possible and merge it or label it as `hacktoberfest-accepted`

**Comment by srihariash999** [comment]
Closed with #10  as initial readme.
